### ISSUE TITLE
BukkitPE support?

### ISSUE THREAD

**Issue by xZeroMCPE** [rutgerkok/Pokkit#6]
Support for BukkitPE? github.com/BukkitPE

or can be added inside the main core?

**Comment by rutgerkok** [comment]
Seeing you are one of the mainainers of BukkitPE, I have to ask:

Why not make BukkitPE compatible with Nukkit?

Porting each and every Nukkit plugin isn't going to work... If you could rename the net.BukkitPE package to cn.nukkit, many Nukkit plugins will instantly start working. If you would also apply all changes made by the Nukkit team since you forked, each and every Nukkit plugin will work. :smiley: 

However, feel free to fork this plugin instead and make it compatible with BukkitPE.

I can see that you invited me to the BukkitPE repo. I'm not going to accept this invitation, as I'm not interested in contributing code to BukkitPE.

**Comment by xZeroMCPE** [comment]
@rutgerkok I wasn't talking about making the plugin able to work with BukkitPE. I was wanting to implement this on the Core itself so it wouldn't be a plugin. But again, thanks for the response.

**Comment by Creeperface01** [comment]
BukkitPE is just fork of nukkkit..
