### ISSUE TITLE
Hello how do I get nukkit-v0.2-SNAPSHOT jar

### ISSUE THREAD

**Issue by Nevgent** [rutgerkok/Pokkit#9]
Could anyone link me the jar?

**Comment by ZINGDING** [comment]
There is no nukkit-v0.2-SNAPSHOT.jar!

**Comment by rutgerkok** [comment]
The latest version of Nukkit can for example be downloaded from here:

http://ci.mengcraft.com:8080/job/nukkit/

(Use the nukkit-1.0-SNAPSHOT.jar link on that page)

At nukkit.io there are several more download options.

@ZINGDING I've unlocked the conversation so that @Nevgent can still reply. I think it is unecessary to lock conversations unless someone is misbehaving.

**Comment by ZINGDING** [comment]
@rutgerkok 
OKAY (:3
